version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

  db:
    image: 'postgres:15.3-alpine'
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  db_data: