version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      REDIS_URL: redis

  db:
    image: postgres:15.3-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:7.2.4-alpine
    command: redis-server
    ports:
      - 6379
    volumes:
      - redis_data:/var/lib/redis/data

volumes:
  db_data:
  redis_data: